### ISSUE TITLE
Refer X-Hasura-User-Id in GraphQL mutations?

### ISSUE THREAD

**Issue by krishkumar** [wawhal/todo-app-graphql-engine-auth0#2]
Consider this request payload when creating a todo.

`{"operationName":"insert_todo","variables":{"objects":[{"task":"test-todo5","user_id":"auth0|5b721527280d8b73e2721281","completed":false}]},"query":"mutation insert_todo($objects: [todo_insert_input!]) {\n  insert_todo(objects: $objects) {\n    affected_rows\n    returning {\n      id\n      task\n      completed\n    }\n  }\n}\n"}`

Is there a way to substitute the` user_id` field in a graphql mutation with a Hasura header value on the server side? Ideally with the `X-Hasura-User-Id` header that already has the same information(https://docs.hasura.io/1.0/graphql/manual/auth/index.html).  

I am looking to avoid sending any more authentication/authorization information than I need to.

**Comment by wawhal** [comment]
Hey @krishkumar!
Since this issue is more on the Hasura GraphQL Engine side, I have [opened an issue](https://github.com/hasura/graphql-engine/issues/216) in the GraphQL Engine repo. It will be tracked there and therefore closing it here.
